### ISSUE TITLE
Restore with different number of segments.

### ISSUE THREAD

**Issue by brosander** [greenplum-db/gpbackup#202]
We backed up a database with 14 segments and would like to restore to one with 16.  Is there a supported way to do this? (Using gpbackup-s3-plugin)

It's failing on restore trying to find segment 14 (0 indexed)

Sorry if this isn't the right avenue for this issue.

I've looked through the documentation and googled to no avail.

**Comment by jmcatamney** [comment]
At the moment, there is no supported way to do that with a simple gprestore command, due to limitations in the underlying `COPY` statements used to restore data.  It's a commonly-requested feature, though, and there are stories in the team's backlog to address it.

One possible workaround in the meantime is to do the restore in two parts: first use gprestore to restore just the metadata to the new cluster, then use gpload to restore the data.  That would require manually retrieving the data from S3 to get it into a state gpload can work with, unfortunately, but if you can do that gpload should handle it just fine.

**Comment by brosander** [comment]
Awesome, thanks!
