### ISSUE TITLE
Error when Downloading

### ISSUE THREAD

**Issue by Sergei-Grigoriev** [greenplum-db/gpbackup#327]
```
go get github.com/greenplum-db/gpbackup/...
# github.com/greenplum-db/gpbackup/restore
/usr/local/go/workspace/src/github.com/greenplum-db/gpbackup/restore/data.go:46:11: undefined: pgx.PgError
/usr/local/go/workspace/src/github.com/greenplum-db/gpbackup/restore/data.go:47:48: undefined: pgx.PgError
```

**Comment by baileygm** [comment]
I've seen this error also but it doesn't seem to have had any impact on the functionality.  
Backup and restore operations have still worked OK

**Comment by kyeap-pivotal** [comment]
Thanks for opening a ticket for this!

We will check it out as soon as possible.

**Comment by kyeap-pivotal** [comment]
Hi Sergei-Grigoriev,

By default in go 1.12 and 1.13 the GO111MODULE environment variable is set to auto The value of this changes if the project directory is in $GOPATH/src or not. There was a small update to the behavior of this environment variable in the go1.13 release notes.

>The GO111MODULE environment variable continues to default to auto, but the auto setting now activates the module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file — even if the current directory is within GOPATH/src. 

What is likely causing the issue is that go is not aware the project is using go modules and reverting to its old method of downloading dependencies where it scans the source code for import paths.

Try using the the command below if gpbackup is located in `$GOPATH` and the version of go is below 1.13.
`GO111MODULE=on  go get github.com/greenplum-db/gpbackup/...`

Alternatively our Makefile command `make depend` will download all dependencies using go modules.
