### ISSUE TITLE
What operations will gpbackup block

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#434]
When I execute `gpbackup`, I found that the truncate operation of table is blocked until the gpbackup is finished. 

Will the truncate of the temporary table be blocked? What other operations will be blocked? 

If the backup takes a long time, the blocked SQL will have a great impact on online biz.

![2020-10-30 18-18-22屏幕截图](https://user-images.githubusercontent.com/11460848/97693567-52d8cf80-1adc-11eb-994d-b4298d3202c4.png)

**Comment by cobolbaby** [comment]
It seems that I have meet the deadlock.

**Comment by jimmyyih** [comment]
When this happens again, could you please run the following queries and paste the output here?
```
SELECT * FROM pg_stat_activity;
SELECT * FROM pg_locks;
```

Also, could you provide the GPDB version and gpbackup command used?  Tracing the $MASTER_DATA_DIRECTORY/pg_log/ to see the order of events would be good too (e.g. the LOCK TABLE (from gpbackup), TRUNCATE , and COPY (from gpbackup) operations on the tables that are blocked).

**Comment by jimmyyih** [comment]
> Will the truncate of the temporary table be blocked? What other operations will be blocked?

Are the TRUNCATE operations only happening on temp tables?  Are they actually temp tables (e.g. CREATE TEMP TABLE) or staging tables?  I don't think the gpbackup utility touches temp tables.

**Comment by jimmyyih** [comment]
Okay, I’ve RCA’d the issue and created a small repro:
```
1: CREATE TABLE foobar (a int);
1: BEGIN;
1: LOCK TABLE foobar IN ACCESS SHARE MODE;

2: TRUNCATE foobar; -- blocking expected
3: COPY foobar TO '/tmp/tempdir/foobar_<SEGID>' ON SEGMENT; -- blocking unexpected
```
In the above example, session 1 is a gpbackup libpq connection, session 2 is the random TRUNCATE, and session 3 is another gpbackup libpq connection created from the `--jobs` flag.  I would have expected the COPY to go through since it’s just trying to read data with an ACCESS SHARE lock but it instead blocks.  Need to think if this is intentional or not (e.g. the ACCESS EXCLUSIVE lock acquire from TRUNCATE could be taking precedence in the lock queue to prevent blocking forever).  If it is intentional, then a `gpbackup --jobs` call would have to correctly assign the COPY to the libpq session that ran the LOCK TABLE... which wouldn't be ideal for parallelism performance (currently, worker threads just grab tables off a single queue to run COPY).

As a workaround, I would suggest either:
1. Do not run gpbackup with the --jobs flag if you plan to have random TRUNCATE operations happening on the same database that is being backed up. We will try to see if we can fix this blocking issue.
-- or --
2. Exclude your staging tables from the backup using the --exclude-table flag.  Note: this would also mean the staging table DDL is not backed up.
-- or --
3. Convert your staging tables into temp tables. The gpbackup utility will then completely skip over them.

**Comment by cobolbaby** [comment]
@jimmyyih 

> could you provide the GPDB version and gpbackup command used? 

- GPDB: 5.28.1
- gpbackup: 1.12.1

> SELECT * FROM pg_stat_activity;
> SELECT * FROM pg_locks;

I recorded the sql in waiting state. See the attachment for details.

[data-1604279009539-active.csv.zip](https://github.com/greenplum-db/gpbackup/files/5472308/data-1604279009539-active.csv.zip)

And the output of pg_lock:

[data-1604278971851.csv.zip](https://github.com/greenplum-db/gpbackup/files/5472312/data-1604278971851.csv.zip)

> Tracing the $MASTER_DATA_DIRECTORY/pg_log/ to see the order of events would be good too

I configured `log_min_messages` in the production env as `fatal`, so there is no valuable information in the logs.

> Are the TRUNCATE operations only happening on temp tables? Are they actually temp tables (e.g. CREATE TEMP TABLE) or staging tables? I don't think the gpbackup utility touches temp tables.

Indeed, the affected is not `temp table`, but some entity tables for intermediate states.

**Comment by jimmyyih** [comment]
Thanks, I was able to confirm that my above RCA (root-cause analysis) and minimal repro is exactly what you are encountering.  Here's a quick analysis of the query output you provided:
```
-- Holder of the AccessShareLock for relation 42160172. This is the
   gpbackup worker thread that ran LOCK TABLE at the very beginning of
   gpbackup. It is currently idle in transaction... presumably because
   there are no more tables in queue.
"relation",189710,42160172,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"128/73594",21079,"AccessShareLock",True,1205259,True,-1

-- Random TRUNCATE on relation 42160172 blocked on AccessExclusiveLock
   request (started 2020-11-01 20:15:36).
"relation",189710,42160172,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"159/115828",26291,"AccessExclusiveLock",False,1206180,True,-1
26291,1206180,TRUNCATE TABLE <relation 42160172>,TRUE,2020-11-01 20:15:36.973469+08,lock

-- Another gpbackup worker (from --jobs flag) running COPY on relation
   42160172 blocked on AccessShareLock request (started 2020-11-01
   20:23:10).
"relation",189710,42160172,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"137/71280",21087,"AccessShareLock",False,1205263,True,-1
21087,1205263,"COPY <relation 42160172> TO PROGRAM 'gzip -c -1 > /gpbackup/20201101200000/gpseg<SEGID>/backups/20201101/20201101200000/gpbackup_<SEGID>_20201101200000_42160172.gz' WITH CSV DELIMITER ',' ON SEGMENT IGNORE EXTERNAL PARTITIONS;",TRUE,2020-11-01 20:23:10.449769+08,lock
```

> Why is the gpbackup version packaged by gpdb 5.28.1 not a new version?

If you mean the Pivotal or VMware Tanzu GPDB 5.28.1, gpbackup stopped being packaged with the GPDB tarball/rpm around gpbackup version 1.13.0.  The reasoning behind this was to give faster gpbackup features/fixes separately without having to depend on the GPDB release cycle (e.g. gpbackup is ready to release a new version but GPDB as a whole is not).  Since gpbackup is packaged and released independently, it is encouraged to always upgrade to the latest version for the newest features and fixes.

**Comment by cobolbaby** [comment]
I checked the release notes of gpbackup and found the latest version, which couldn't solve the problem. It seems that it is currently impossible to enjoy the benefits of multi-process.

In addition, can you provide some design instructions and development specifications for gpbackup so that I can also locate problems and submit some bugfixes.

**Comment by oakbarrett** [comment]
re:   temp tables, true temp tables are created in a pg_temp* schema.    Below is a list of schemas which gpbackup does not backup

https://gpdb.docs.pivotal.io/backup-restore/1-20/admin_guide/managing/backup-gpbackup.html

<img width="745" alt="Screen Shot 2020-11-02 at 10 41 04 AM" src="https://user-images.githubusercontent.com/1195118/97906158-0cf85300-1cf8-11eb-9232-d0da59c2d332.png">


To add onto Jimmy's workarounds of the --jobs flag, you can run multiple gpbackups in parallel... for instance, if your database has 5 schemas, you can kick off 5 gpbackups using the --include-schema   flag. 

We will continue to look into the --jobs / Truncate issue.

**Comment by cobolbaby** [comment]
It seems that I need to temporarily adjust the backup script, thank you for the solution.

**Comment by cobolbaby** [comment]
@jimmyyih @oakbarrett  Today I found that the following commands also causes lock. Does the S3 plugin also have such problems?

```
 /usr/local/greenplum-db/bin/gpbackup --dbname F3_BDC --plugin-config /opt/greenplum/config/s3_backup.yml --leaf-partition-data --with-stats --quiet --jobs 1
```

**Comment by jimmyyih** [comment]
That seems very unlikely to deadlock from my knowledge.  Were you able to confirm by looking at `pg_stat_activity`?  You could check with something like `SELECT * FROM pg_stat_activity WHERE application_name like 'gpbackup%'` and check the `waiting_reason`.  If you do find it waiting on a lock, it would be good to check `pg_locks` to see what session has a lock on the blocked table and then check back on `pg_stat_activity` to reference.

If you're asking if gpbackup with S3 plugin takes locks even with `--jobs 1`, then yes.  The gpbackup utility will always try to take AccessShareLock at the beginning for all tables being backed up.

**Comment by cobolbaby** [comment]
I'm curious why operations like delete and update are not blocked.

**Comment by jimmyyih** [comment]
> In addition, I'm curious why operations like delete and update are not blocked.

DELETE and UPDATE take ExclusiveLock (lesser RowExclusiveLock if Global Deadlock Detector is enabled) which does not conflict with gpbackup's AccessShareLock obtained in the beginning `LOCK TABLE` step and the `COPY TO` step.  The lock queue is a FIFO queue and is dependent on the session's current acquired lock.
