### ISSUE TITLE
Incremental backups are same size (or bigger) as full backup

### ISSUE THREAD

**Issue by NoFWayMan** [greenplum-db/gpbackup#492]
Hello! I'm using Greenplum 6.14 and latest Backup and Restore (1.20.3). 
So here is my problem step-by-step:
1. I created a test database with 1000 tables and random content in rows in it
2. gpbackup --dbname test_db_100g --jobs 8 --leaf-partition-data
3. Added another 300 tables in DB
4. gpbackup --dbname test_db_100g --jobs 8 --leaf-partition-data  --incremental
Then, i checked size of both backups - incremental backup is bigger than full (first) backup
I decide to try another way and make some changes in existing tables, instead of adding new ones. So:
1. Same two steps as in first example
2. Change content of 300 random rows
3. gpbackup --dbname test_db_100g --jobs 8 --leaf-partition-data  --incremental
And i get a same result, nothing changed. My full backup is 36 mb and incremental backup is 36 mb as well.
Am i doing something wrong? 

P.S. Sorry for bad english :)

**Comment by jimmyyih** [comment]
Hello,

Most likely what you're seeing is the limitation of incremental backup.  The feature only works for append-optimized row/column tables (e.g. `CREATE TABLE foo_ao_row (a int) WITH (appendonly=true)` or `CREATE TABLE foo_ao_col (a int) WITH (appendonly=true, orientation=column)`).  See https://gpdb.docs.pivotal.io/backup-restore/1-20/admin_guide/managing/backup-gpbackup-incremental.html for more information.

As an explanation for why this limitation exists: Only append-optimized tables have reliable metadata to determine if data has been inserted, deleted, or updated (via append-optimized auxiliary metadata tables in the `pg_aoseg` schema).  For Heap tables, there hasn't been a reliable way to retrieve the same information.  The closest is the `pg_stat_all_tables` view provided by the statistics collector... but there are issues with using it.  We do plan on supporting incremental backup for heap tables in the future though when `pg_stat_all_tables` is fixed in GPDB (there were some patches committed for GPDB 7 but I'm not sure they fully fixed the view) or some other mechanism is introduced.

- Jimmy

**Comment by NoFWayMan** [comment]
Yes, it works when i create append-only tables, and then update them. Thank you for your help!
