### ISSUE TITLE
gpbackup and GPCC integration support

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpbackup#518]
Hi, Team,

Our customer suggest that GPCC can integrate DB backup integration such as housekeeping or backup/restore.

Maybe your team can consider it.

Regarfds.

**Comment by jimmyyih** [comment]
This is not the correct place to ask for this feature request.  Would suggest sending this commercial feature request to VMware Tanzu support instead (it'll get prioritized better there since we have no say or access to Tanzu GPCC).  FWIW, I personally think it would be great to see the integration happen.
