### ISSUE TITLE
`gpbackup` does not copy `gpbackup_history.yaml` to smdw host

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpbackup#520]
Hi,

One of our subscribed customers previously perform high availability test on mdw/smdw nodes.

And they find that `gpbackup_history.yaml` file "disappears" on smdw, which is horrible because they utilize DDBoost plugin and backup file management `gpbackup_manager` is totally relying on this file.

Can gpbackup team fix this bug?

Thanks.

**Comment by jimmyyih** [comment]
For `gpbackup_manager` or DDBoost plugin issues, it's recommended to go through Tanzu support as they are closed-source products whereas this repository is for open source gpbackup (and the public S3 plugin).  However, the history file plays a big role in incremental backups so let's focus mainly on the history file for this discussion thread.

> And they find that gpbackup_history.yaml file "disappears" on smdw,

This is a somewhat documented limitation:
> gpbackup_history.yaml - Stored on the Greenplum Database master host in the Greenplum Database master data directory. This file is not backed up by gpbackup.

There is no replication of the history file to the standby master.  If the standby master is activated, the history file will not be there (but can be copied over from the inactive old master if available and not corrupted).  It's usually best practice to make sure that the cluster is in the preferred state (the preferred master is the active master and the preferred primary segments are the active primary segments) before doing any operations relating to gpbackup.  However, do note though that `gprecoverseg` does not work for master/standby recovery so it's a good idea to create a copy of the history file before failing back to the old master since failing back usually requires running `gpinitstandby -r` which I believe fully deletes the old master (containing the history file) and then regular `gpinitstandby` does a `pg_basebackup` of the active master (the standby master).

As for "fixing" this bug, the only reasonable thing I can think of is to add an enhancement to `rsync` the history file to the standby master via an optional flag.  At least that way we'll have a copy instead of users having to manually doing it themselves.  @oakbarrett
