### ISSUE TITLE
Retry to execute BackupSingleTableData when copyErr is not nil

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#574]
`[CRITICAL]:-ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)` arises with the code below, the transaction needs to be rolled back. Do I need to do connectionPool.MustRollback(whichConn), but how can I guarantee the snapshot consistency? @jimmyyih @kyeap-vmware 

```go
		// Retry BackupSingleTableData 3 times if copy fails
		for i, attempts := 1, 3; i <= attempts; i++ {
			if i > 1 {
				time.Sleep(time.Duration(5000*(i-1)) * time.Millisecond)
			}
			err := BackupSingleTableData(table, rowsCopiedMaps[whichConn], &counters, whichConn)
			if err != nil {
				gplog.Error(err.Error())

				copyErr = err

				// ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
				// connectionPool.MustRollback(whichConn)

				continue
			}
			copyErr = nil
			break
		}
```

_Originally posted by @cobolbaby in https://github.com/greenplum-db/gpbackup/issues/478#issuecomment-1210525076_

**Comment by jimmyyih** [comment]
> but how can I guarantee the snapshot consistency?

In GPDB 6.21.0, distributed snapshot export/import was added and then implemented in gpbackup in this patch: https://github.com/greenplum-db/gpbackup/commit/f9f1c2dee157200115e882eab2e6fbd8c4945e68.  IIRC, the patch handles aborted transactions and resetting of the distributed snapshot on workers.  However, there is no retry for a failed table backup unless the failure is due to the worker being unable to get AccessShareLock.  A true backup retry could be tricky to implement but doable (probably just need to delete the corrupted backup data for the table on all segments and attempt the COPY again with a new --backup-retry-attempts flag).

@jmcatamney @AJR-VMware whom are the current maintainers for any follow-up.
